name: 'Frontend React Build Artefato'

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

jobs: 
  - job: BuildAndTest
    displayName: 'Publicação do Artefato de React Front'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '20.x'
      - task: CmdLine@2
        inputs:
          script: 'cd src/frontend && npm install'
      - task: CmdLine@2
        inputs:
          script: 'cd src/frontend && npm run build'
          displayName: 'Gerando Artefato de Build'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.SourcesDirectory)/src/frontend/dist'
          artifact: 'react-EventPlan'
          publishLocation: 'pipeline-prod'
